### ISSUE TITLE
debconf task prevents use of ansible-ferm on non debian distributions

### ISSUE THREAD

**Issue by JeanVEGA** [debops/ansible-ferm#104]
```
- name: Configure ferm status in debconf
  debconf:
    name: 'ferm'
    question: 'ferm/enable'
    vtype: 'boolean'
    value: '{{ "yes" if ferm__enabled|bool else "no" }}'
```
has no option to be skipped, except for entirely disabling the role. I am using debops on CentOS and direct use of debconf would require a custom fork.

Would it be possible to add a skip option for it?

Thanks
