### ISSUE TITLE
comma-separated Connection state doesn't work

### ISSUE THREAD

**Issue by laukaichung** [debops/ansible-ferm#115]
From the [document](https://docs.debops.org/en/latest/ansible/roles/ansible-ferm/docs/rules.html#custom-rules)

````
state

Optional. Connection state which should be matched. 
Possible values: INVALID, ESTABLISHED, NEW, RELATED, UNTRACKED 
or comma-separated combination thereof.
````
So I tried this:
````
ferm__rules:
  - type: 'accept'
    name: 'allow_tcp_9200'
    comment: 'Allow outgoing Elasticsearch api port'
    dport: '9200'
    chain: 'INPUT'
    protocol: 'tcp'
    target: 'ACCEPT'
    state: 'NEW,ESTABLISHED'
````
But it complained that the comma is invalid. I had to put the states in `()` without a comma to get it to work.
````
ferm__rules:
  - type: 'accept'
    name: 'allow_tcp_9200'
    comment: 'Allow outgoing Elasticsearch api port'
    dport: '9200'
    chain: 'INPUT'
    protocol: 'tcp'
    target: 'ACCEPT'
    state: '(NEW ESTABLISHED)'
````

**Comment by drybjed** [comment]
Hi. I checked your example and you're right, it breaks. It seems to be a documentation bug; this section of the documentation [was added about two years ago](https://github.com/debops/ansible-ferm/commit/42eb57c2c90653d3623a4b5bf087b58f29b2e94f) and hasn't been updated since.

You should be able to use a YAML list instead of this awkward string:

```yaml
---
ferm__rules:
  - type: 'accept'
    name: 'allow_tcp_9200'
    state: [ 'NEW', 'ESTABILISHED' ]
```
This syntax works OK.
